In [5]:
import numpy as np

#%% Replace greater than 3 with 100

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

my_test = np.where(a >= 3)

# my_test

a[ np.where(a >= 3) ] = np.ones( len( np.where(a >= 3) ) )*100
a

array([  1,   2, 100,   2, 100, 100, 100, 100, 100, 100])

In [ ]:
a = np.array([[1,2,3,5,3,4,3,4,5,6],
             [7,2,10,2,7,4,9,4,9,8]])
my_x = np.where(a > 8)
# my_x
##Replace All elements greater than 4 with constant value of 10
a[ np.where(a>4) ] = 10
a
# type(my_x)

array([[ 1,  2,  3, 10,  3,  4,  3,  4, 10, 10],
       [10,  2, 10,  2, 10,  4, 10,  4, 10, 10]])

In [16]:

a = np.array([2, 6, 1, 9, 10, 3, 27])
# a[ (a >= 5) & (a <= 10) ]

a[ np.where( (a >= 5) & (a <= 10) ) ]

array([ 6,  9, 10])

In [ ]:
a = np.array([[1,2,3,2,3,4,3,4,5,6],
             [7,2,10,2,7,4,9,4,9,8]])

# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

# square each element
print ("Squaring each element:", a**2)

print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)

In [17]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())

# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [18]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[4, 3],
            [2, 1]])

# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [19]:
# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [21]:
a = np.array([[1, 4, 2],
              [3, 4, 6],
              [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(a, axis =1))

# sort array column-wise
print ("Column-wise sorted array:\n",
                np.sort(a, axis = 0))

Array elements in sorted order:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [23]:
# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
arr

array([(b'Hrithik', 2009, 8.5), (b'Ajay', 2008, 8.7),
       (b'Pankaj', 2008, 7.9), (b'Aakash', 2009, 9. )],
      dtype=[('name', 'S10'), ('grad_year', '<i8'), ('cgpa', '<f8')])

In [24]:
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]


In [25]:
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']),)

Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]
