In [1]:
import numpy as np
zeros_arr = np.zeros( (5,5,5))

In [2]:
zeros_arr

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:

# zeros_arr_int = np.zeros((5),dtype=int)
# zeros_arr_int

# ones_arr =  np.ones((5,5))
# #%%
# constant_arr = np.full( (2,3,4), 5)
# constant_arr

# random_arr = np.random.random((2,3))

# arange_arr = np.arange(0, 10).reshape(2,5)
# arange_arr

# arange_arr.reshape(3,5)

# linspace_arr = np.linspace(0, 10, 100)
# linspace_arr

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [14]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

three_d_array = arr.reshape(1, 4, 3)
three_d_array

array([[[1, 2, 3],
        [4, 5, 2],
        [4, 2, 1],
        [2, 0, 1]]])

In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 1, 0])

10


In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])

10


In [19]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
# temp = arr[:, 2]
# temp
temp = arr[:2, :2]
temp

array([[-1. ,  2. ],
       [ 4. , -0.5]])

In [ ]:
# Slicing array
# temp = arr[ [0,1], 0:4:2]
# print(temp)
# temp = arr[ [0,1],[2,3]]
# print(temp)
# #%%
print(arr[[0, 1, 2, 3], [3, 2, 1, 0]])

[4. 6. 0. 3.]


In [25]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])


arr[:2, :2] = np.zeros( (2,2) )
# arr

print(arr[arr > 0])

[4.  6.  2.6 7.  8.  3.  4.  2. ]


In [26]:
#%% Find odd numbers, replace odd numbers with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
print(arr[arr%2 == 1])
arr[arr%2 == 1] = -1
arr

[1 3 5 7 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])